# Generated by Django 3.2.8 on 2021-11-14 13:45

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "acquisition_year",
                    models.PositiveIntegerField(
                        validators=[api.validators.validate_year]
                    ),
                ),
                ("kilometers", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "CNP",
                    models.PositiveBigIntegerField(
                        unique=True, validators=[api.validators.validate_cnp]
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        validators=[api.validators.validate_date]
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        auto_now_add=True,
                        validators=[api.validators.validate_date],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workmanship_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[api.validators.validate_price],
                    ),
                ),
                (
                    "parts_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[api.validators.validate_price],
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "workmanship_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[api.validators.validate_price],
                    ),
                ),
                (
                    "parts_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[api.validators.validate_price],
                    ),
                ),
                (
                    "id_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="api.car",
                    ),
                ),
                (
                    "id_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="api.client",
                    ),
                ),
            ],
        ),
    ]
