# Generated by Django 3.2.9 on 2021-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id_car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='parts_discount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='workmanship_discount',
        ),
    ]
